[package]
name = "templating-engine"
version = "0.1.0"
edition = "2021"

[features]
default = ["simd"]

simd = []

[dependencies]
nom = "7.1.3"

[dev-dependencies]
insta = "1.40.0"
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "parser"
harness = false